# Generated by Django 2.0.5 on 2018-06-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReservationRede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=5)),
                ('details', models.CharField(max_length=200)),
                ('reservation_date', models.DateTimeField()),
                ('status', models.CharField(default='pendente', max_length=20)),
            ],
        ),
    ]
